addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
    - ARQUILLIAN_DOCKER_EXTENSION_ENABLED=true

jdk: oraclejdk8

language: java

services:
    - docker

sudo: required

before_install:
    - 'if [ "$TRAVIS_EVENT_TYPE" = "push" ] && [ "$TRAVIS_BRANCH" != "master" ]; then
          echo "Terminating build since there is also a pull request build running.";
          travis_terminate 0;
       fi'

    # Install Catch Reports

    - curl -O https://liferay-labs.github.io/reports-catcher/catch-reports.sh
    - chmod +x catch-reports.sh

    # Build Docker Image and Run
    
    - ./gradlew buildAppDocker runDocker -Pdocker.image.name=$DOCKER_IMAGE_NAME -Pdocker.image.version=latest -Pdocker.org=$DOCKER_ORG

install: true

script:
    - ./gradlew testIntegration

    # Get test coverage results

    - ./gradlew dumpJacoco
    - ./gradlew coveralls
    
    # Publish docker image to Docker Hub

    - 'if [ "$TRAVIS_EVENT_TYPE" = "push" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
           ./gradlew pushAppDockerImage -Pdocker.image.name=$DOCKER_IMAGE_NAME -Pdocker.org=$DOCKER_ORG;
       fi'

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

after_script:
    - ./catch-reports.sh